services:
  - type: web
    name: oi-dashboard-backend
    env: node
    plan: free # Can be changed to 'pro' for more memory/CPU
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_DATA
        value: false
      - key: MONGODB_URI
        sync: false
      - key: NSE_URL
        value: https://www.nseindia.com/api/option-chain-indices?symbol=
      - key: OPTION_CHAIN_URL
        value: https://www.nseindia.com/option-chain
